<?php
/**
 * This file is part of Glugox.
 *
 * (c) Glugox <glugox@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

// @codingStandardsIgnoreFile
?>
<script>
    require([
        "jquery",
        'Magento_Ui/js/modal/confirm',
        "jquery/ui",
        "Glugox_Integration/js/integration"
    ], function ($, Confirm) {

        window.glugoxIntegration = new GlugoxIntegration();

    });
</script>

<div id="glugox-integration-popup-container" style="display: none;"></div>